#!/bin/sh
set -e;

POSTGRES_DB=dv1562_lab2_db_1;
POSTGRES_USER=docker;
POSTGRES_PASSWORD=docker;

psql -U postgres -v ON_ERROR_STOP=1 <<-EOSQL
    DROP DATABASE IF EXISTS $POSTGRES_DB;
    DROP USER IF EXISTS $POSTGRES_USER;
EOSQL

psql -U postgres -v ON_ERROR_STOP=1 <<-EOSQL
    CREATE USER $POSTGRES_USER WITH PASSWORD '$POSTGRES_PASSWORD';
    CREATE DATABASE $POSTGRES_DB WITH OWNER $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_DB TO $POSTGRES_USER;
EOSQL

psql -v ON_ERROR_STOP=1 --username $POSTGRES_USER --dbname $POSTGRES_DB <<-EOSQL
    CREATE TABLE IF NOT EXISTS requests (
        id SERIAL PRIMARY KEY,
        city VARCHAR(100) NOT NULL,
        timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
EOSQL
